# Generated by Django 5.0.8 on 2024-10-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('slug', models.SlugField(max_length=56, null=True)),
                ('province_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_waist', models.CharField(choices=[('0', '۰۰-بدون درد'), ('1', '۰۱-خیلی نرم'), ('2', '۰۲-ناراحت کننده'), ('3', '۰۳-قابل تحمل'), ('4', '۰۴-پریشانی'), ('5', '۰۵-بسیار ناراحت کننده'), ('6', '۰۶-شدیدتر'), ('7', '۰۷-خیلی شدید'), ('8', '۰۸-کاملا وحشتناک'), ('9', '۰۹-طاقت فرسا'), ('10', '۱۰-وصف ناپذیر')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('slug', models.SlugField(max_length=56, null=True)),
                ('tel_prefix', models.CharField(max_length=56, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='سن')),
                ('martial_status', models.CharField(choices=[('M', 'متأهل'), ('S', 'مجرد')], max_length=20, verbose_name='وضعیت تأهل')),
                ('smoke', models.CharField(choices=[('Y', 'بله'), ('N', 'خیر')], max_length=20, verbose_name='آیا سیگار مصرف میکنید؟')),
                ('pain_sckelete', models.CharField(choices=[('Y', 'بله'), ('N', 'خیر')], max_length=20, verbose_name='آیا سابقه دردهای عضلانی اسکلتی پیش از آن داشته اید ؟ ')),
                ('pain_family_waist', models.CharField(choices=[('Y', 'بله'), ('N', 'خیر')], max_length=20, verbose_name='آیا سابقه فامیلی درد کمر در فامیل درجه یک داشته اید؟')),
                ('spain_sargery', models.CharField(choices=[('Y', 'بله'), ('N', 'خیر')], max_length=20, verbose_name='آیا سابقه جراحی ستون فقرات در فامیل درجه یک داشته اید؟')),
                ('back_pain_after_impact', models.CharField(choices=[('Y', 'بله'), ('N', 'خیر')], max_length=20, verbose_name='آیا کمر درد شما به دنبال ضربه ایجاد شده است ؟')),
                ('back_pain', models.CharField(max_length=20, verbose_name='چند روز از شروع کمر درد شما میگذرد؟')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='سن')),
                ('martial_status', models.CharField(max_length=55, verbose_name='وضعیت تأهل')),
                ('province', models.CharField(max_length=75, verbose_name='محل سکونت/استان')),
                ('city', models.CharField(max_length=75, verbose_name='محل سکونت/شهر')),
                ('degree', models.CharField(max_length=75, verbose_name='مقطع تحصیلی')),
                ('job', models.CharField(max_length=75, verbose_name='شغل پیش از شروع خدمت')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('height', models.IntegerField(verbose_name='قد')),
                ('bmi', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('time_goes', models.IntegerField(verbose_name='مدت زمان سپری شده از خدمت')),
                ('smoke', models.CharField(max_length=12, verbose_name='آیا سیگار مصرف میکنید؟')),
                ('sleep', models.CharField(max_length=75, verbose_name='وضعیت خواب ')),
                ('history_skeleton_pain', models.CharField(max_length=11, verbose_name='سابقه ی درد های عصلانی استخوانی')),
                ('spain_surgery', models.CharField(max_length=11, verbose_name='سابقه ی جراحی ستون فقرات')),
                ('pain_family', models.CharField(max_length=11, verbose_name='سابقه فامیلی درد های عضلانی')),
                ('back_pain_after_impact', models.CharField(max_length=11, verbose_name='آیا کمر درد شما به دنبال ضربه ایجاد شده است؟')),
                ('back_pain', models.IntegerField(verbose_name='چند روز از شروع کمر درد شما میگذرد ؟')),
                ('pain_waist', models.IntegerField()),
                ('odi', models.IntegerField()),
                ('disability_level', models.CharField(max_length=150)),
                ('depression', models.CharField(max_length=57, verbose_name='افسردگی')),
                ('anxiety', models.CharField(max_length=57, verbose_name='اضطراب')),
                ('stress', models.CharField(max_length=57, verbose_name='استرس')),
                ('chronic', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResultFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='سن')),
                ('martial_status', models.CharField(blank=True, max_length=55, null=True, verbose_name='وضعیت تأهل')),
                ('province', models.CharField(blank=True, max_length=75, null=True, verbose_name='محل سکونت/استان')),
                ('city', models.CharField(blank=True, max_length=75, null=True, verbose_name='محل سکونت/شهر')),
                ('degree', models.CharField(blank=True, max_length=75, null=True, verbose_name='مقطع تحصیلی')),
                ('job', models.CharField(blank=True, max_length=75, null=True, verbose_name='شغل پیش از شروع خدمت')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='وزن')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='قد')),
                ('bmi', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('time_goes', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان سپری شده از خدمت')),
                ('smoke', models.CharField(blank=True, max_length=12, null=True, verbose_name='آیا سیگار مصرف میکنید؟')),
                ('sleep', models.CharField(blank=True, max_length=75, null=True, verbose_name='وضعیت خواب ')),
                ('history_skeleton_pain', models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه ی درد های عصلانی استخوانی')),
                ('spain_surgery', models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه ی جراحی ستون فقرات')),
                ('pain_family', models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه فامیلی درد های عضلانی')),
                ('back_pain_after_impact', models.CharField(blank=True, max_length=11, null=True, verbose_name='آیا کمر درد شما به دنبال ضربه ایجاد شده است؟')),
                ('back_pain', models.IntegerField(blank=True, null=True, verbose_name='چند روز از شروع کمر درد شما میگذرد ؟')),
                ('pain_waist', models.IntegerField(blank=True, null=True)),
                ('odi', models.IntegerField(blank=True, null=True)),
                ('disability_level', models.CharField(blank=True, max_length=150, null=True)),
                ('depression', models.CharField(blank=True, max_length=57, null=True, verbose_name='افسردگی')),
                ('anxiety', models.CharField(blank=True, max_length=57, null=True, verbose_name='اضطراب')),
                ('stress', models.CharField(blank=True, max_length=57, null=True, verbose_name='استرس')),
                ('prediction', models.CharField(blank=True, choices=[('Chronic', 'chronic'), ('Acute', 'acute')], default='Chronic', max_length=155, null=True)),
                ('percentage', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahsilat', models.CharField(choices=[('ابتدایی', 'ابتدایی'), ('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکتری', 'دکتری')], max_length=50)),
                ('weight', models.CharField(max_length=150, verbose_name='وزن')),
                ('height', models.CharField(max_length=150, verbose_name='قد')),
                ('time_goes', models.CharField(max_length=150, verbose_name='مدت زمان سپری شده از خدمت:')),
                ('job', models.CharField(max_length=150, verbose_name='شغل')),
                ('sleep', models.CharField(choices=[('خواب کافی دارم', 'خواب کافی دارم'), ('خوب نمیخوابم', 'خوب نمیخوابم'), ('گاهی خوب میخوابم و گاهی بد', 'گاهی خوب میخوابم و گاهی بد')], max_length=30, verbose_name='وضعیت خواب خود را چگونه میبینید؟')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
    ]
