# Generated by Django 5.0.8 on 2024-08-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='pain_intensity_score',
        ),
    ]
