# Generated by Django 5.0.8 on 2024-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='height',
            field=models.IntegerField(verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='weight',
            field=models.IntegerField(verbose_name='وزن'),
        ),
    ]
