# Generated by Django 5.0.8 on 2024-08-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userresult_pain_intensity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martial_status', models.CharField(max_length=55, verbose_name='وضعیت تأهل')),
                ('province', models.CharField(max_length=75, verbose_name='محل سکونت/استان')),
                ('city', models.CharField(max_length=75, verbose_name='محل سکونت/شهر')),
                ('degree', models.CharField(max_length=75, verbose_name='مقطع تحصیلی')),
                ('job', models.CharField(max_length=75, verbose_name='شغل پیش از شروع خدمت')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('height', models.IntegerField(verbose_name='قد')),
                ('bmi', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('time_goes', models.IntegerField(verbose_name='مدت زمان سپری شده از خدمت')),
                ('smoke', models.CharField(max_length=12, verbose_name='آیا سیگار مصرف میکنید؟')),
                ('sleep', models.CharField(max_length=75, verbose_name='وضعیت خواب ')),
                ('history_skeleton_pain', models.CharField(max_length=11, verbose_name='سابقه ی درد های عصلانی استخوانی')),
                ('spain_surgery', models.CharField(max_length=11, verbose_name='سابقه ی جراحی ستون فقرات')),
                ('pain_family', models.CharField(max_length=11, verbose_name='سابقه فامیلی درد های عضلانی')),
                ('back_pain_after_impact', models.CharField(max_length=11, verbose_name='آیا کمر درد شما به دنبال ضربه ایجاد شده است؟')),
                ('back_pain', models.IntegerField(verbose_name='چند روز از شروع کمر درد شما میگذرد ؟')),
                ('pain_waist', models.IntegerField()),
                ('odi', models.IntegerField()),
                ('disability_level', models.CharField(max_length=150)),
                ('depression', models.CharField(max_length=57, verbose_name='افسردگی')),
                ('anxiety', models.CharField(max_length=57, verbose_name='اضطراب')),
                ('stress', models.CharField(max_length=57, verbose_name='استرس')),
                ('chronic', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
