# Generated by Django 5.0.8 on 2024-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userresultfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresultfinal',
            name='anxiety',
            field=models.CharField(blank=True, max_length=57, null=True, verbose_name='اضطراب'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='back_pain',
            field=models.IntegerField(blank=True, null=True, verbose_name='چند روز از شروع کمر درد شما میگذرد ؟'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='back_pain_after_impact',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='آیا کمر درد شما به دنبال ضربه ایجاد شده است؟'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='city',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='محل سکونت/شهر'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='degree',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='depression',
            field=models.CharField(blank=True, max_length=57, null=True, verbose_name='افسردگی'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='disability_level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='history_skeleton_pain',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه ی درد های عصلانی استخوانی'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='job',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='شغل پیش از شروع خدمت'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='martial_status',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='وضعیت تأهل'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='odi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='pain_family',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه فامیلی درد های عضلانی'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='pain_waist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='province',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='محل سکونت/استان'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='sleep',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='وضعیت خواب '),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='smoke',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='آیا سیگار مصرف میکنید؟'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='spain_surgery',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='سابقه ی جراحی ستون فقرات'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='stress',
            field=models.CharField(blank=True, max_length=57, null=True, verbose_name='استرس'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='time_goes',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان سپری شده از خدمت'),
        ),
        migrations.AlterField(
            model_name='userresultfinal',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
